feat/ログイン、ログアウト、アカウント作成
mct-joken/jkojs-front pull request #34
Opened 2023-03-07 20:28 UTC by kiji-haru

kojs-backendのログイン、ログアウト、アカウント作成のAPIを叩けるようになりました。

2023-03-07 20:30 UTC, kiji-haru commented
テストするとき
一番最初はヘッダーのログインのボタンを押してとんだページにあるアカウント作成のリンクからアカウントを新規に作成してください。
それではおやすみ

2023-03-07 23:16 UTC, laminne requested changes
エンドポイントが古い気がする

2023-03-08 02:02 UTC, laminne requested changes
URL決めうちだけ直して

2023-03-08 08:05 UTC, laminne approved these changes

2023-03-08 08:05 UTC, laminne commented on src/pages/mypage.tsx
> +    window.location.href = "/";
ログインページに飛ばすべきでは？

2023-03-10 02:32 UTC, laminne commented
あれ、これまだマージしてないの

2023-03-14 14:05 UTC, merged